---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-action-groups
  namespace: logging
type: Opaque
stringData:
  action_groups.yml: |
    _meta:
      type: "actiongroups"
      config_version: 2
