---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-tenats
  namespace: logging
type: Opaque
stringData:
  tenants.yml: |
    ---
    _meta:
      type: "tenants"
      config_version: 2

    # Define your tenants here

    ## Demo tenants
    admin_tenant:
      reserved: false
      description: "Demo tenant for admin user"